from software_defect_prediction import logger
from software_defect_prediction.pipeline.stage_01_dataingestion_pipeline import DataIngestionPipeline


dataingestion_pipeline = DataIngestionPipeline()
dataingestion_pipeline.main()
