artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.usercontent.google.com/u/0/uc?id=1-16D_BjR9RGJJ-UySEqFKWSO7ElDmmVs&export=download
  source_URL_file_name : software_defect_detection.zip
  source_URL_unzip_file_name : train.csv
  local_data_file: software_defect_detection.csv
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  source_file_path: artifacts/data_ingestion/software_defect_detection.csv
  input_file_name: software_defect_detection.csv
  STATUS_FILE : artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  source_file_path: artifacts/data_validation/software_defect_detection.csv
  input_file_name: software_defect_detection.csv

model_trainer:
  root_dir: artifacts/model_trainer
  source_file_path: artifacts/data_transformation/
  train_file : train_data.csv
  test_file : test_data.csv

model_evaluation:
  root_dir : artifacts/model_evaluation
  source_file_path : artifacts/model_trainer/
  model_file : random_forest_model.joblib
  train_file : train_data.csv
  test_file : test_data.csv
  perf_metrics_file : perf_metrics.json