artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.usercontent.google.com/u/0/uc?id=1-16D_BjR9RGJJ-UySEqFKWSO7ElDmmVs&export=download
  source_URL_file_name : software_defect_detection.zip
  source_URL_unzip_file_name : train.csv
  local_data_file: software_defect_detection.csv
  unzip_dir: artifacts/data_ingestion